// <auto-generated />
using System;
using LibraryManagement.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryManagement.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241215014617_SEEDDATA")]
    partial class SEEDDATA
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryManagement.Domain.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AvailableCopies")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a2a57b25-56ad-4481-9bdc-244bac2ad32b"),
                            Author = "F. Scott Fitzgerald",
                            AvailableCopies = 5,
                            Genre = "Fiction",
                            ISBN = "9780743273565",
                            Language = "English",
                            PageCount = 180,
                            PublicationYear = 1925,
                            Publisher = "Scribner",
                            Summary = "The Great Gatsby is a novel by American writer F. Scott Fitzgerald. Set in the Jazz Age on Long Island, near New York City, the novel depicts first-person narrator Nick Carraway's interactions with mysterious millionaire Jay Gatsby and Gatsby's obsession to reunite with his former lover, Daisy Buchanan.",
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = new Guid("d1b81886-68ba-4300-949b-32650f18a7f0"),
                            Author = "Harper Lee",
                            AvailableCopies = 3,
                            Genre = "Fiction",
                            ISBN = "9780060935467",
                            Language = "English",
                            PageCount = 281,
                            PublicationYear = 1960,
                            Publisher = "Harper Perennial Modern Classics",
                            Summary = "To Kill a Mockingbird is a novel by Harper Lee published in 1960. Instantly successful, widely read in high schools and middle schools in the United States, it has become a classic of modern American literature, winning the Pulitzer Prize.",
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            Id = new Guid("eb0b3ad7-b456-4974-9b3d-b965ddc1b549"),
                            Author = "George Orwell",
                            AvailableCopies = 2,
                            Genre = "Fiction",
                            ISBN = "9780451524935",
                            Language = "English",
                            PageCount = 328,
                            PublicationYear = 1949,
                            Publisher = "Signet Classic",
                            Summary = "1984 is a dystopian social science fiction novel by English novelist George Orwell. It was published on 8 June 1949 by Secker & Warburg as Orwell's ninth and final book completed in his lifetime.",
                            Title = "1984"
                        },
                        new
                        {
                            Id = new Guid("2639e78c-12d7-4337-9d9f-1ac7b90d1177"),
                            Author = "Jane Austen",
                            AvailableCopies = 4,
                            Genre = "Fiction",
                            ISBN = "9780141439518",
                            Language = "English",
                            PageCount = 279,
                            PublicationYear = 1813,
                            Publisher = "Penguin Classics",
                            Summary = "Pride and Prejudice is a romantic novel of manners written by Jane Austen in 1813. The novel follows the character development of Elizabeth Bennet, the dynamic protagonist of the book who learns about the repercussions of hasty judgments and comes to appreciate the difference between superficial goodness and actual goodness.",
                            Title = "Pride and Prejudice"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
